// Engine request authentication + outbound-URL (SSRF) + media-cap guards.
//
// ── Authentication model ──
// The engine is reachable on the public internetadian? No — it is reachable
// on the public internet, but must refuse anyone who isn't the web app's
// proxy (which the user's browser talks to) or a holder of a per-workspace
// API key:
//
//   1. INTERNAL  — apps/web calls the engine through its `WA_WORKER` service
//      binding. The web worker attaches `Authorization: Bearer
//      <ENGINE_INTERNAL_SECRET>` plus `X-Engine-Workspace: <workspaceId>`.
//      The engine resolves this to an "internal" caller scoped to exactly
//      that workspace. ENGINE_INTERNAL_SECRET lives in BOTH apps'
//      wrangler.jsonc (committed dev default + comment) and is overridable
//      per-app with `wrangler secret put ENGINE_INTERNAL_SECRET`. Because
//      the secret is what grants workspace-scope on internal calls, the
//      web proxy must ALWAYS forward the caller's real workspaceId — never
//      trust a header the browser could set.
//
//   2. API       — an external integration holds a per-workspace key
//      generated by apps/web (see tenancy.ts apiKeys). The raw key is shown
//      once at creation; only its SHA-256 hash is stored. The integration
//      sends `Authorization: Bearer wa_...`; we hash it and look it up in
//      api_keys to recover the workspaceId together with a lastUsedAt bump.
//      These keys drive /agent/*, /search, /media/* and
//      /broadcast/:id/start for one workspace only.
//
// Everything except GET /health requires one of the two caller kinds.
//
// ── SSRF ──
// The engine fetches user-supplied outbound URLs: agent webhook-tool calls,
// webhook deliveries)Skip, and broadcast send-media. Without a guard those
// could be pointed at loopback/cloud-metadata (169.254.169.254) to read
// secrets from the network the worker lives on. We block IP literals in
// private/loopback/link-local ranges, IPv6 link-local/ULA, localhost and
// reserved TLDs. (We can't resolve arbitrary DNS here, so a hostname that
// resolves to a private IP isn't caught — note as a known residual.)

import { createDb, eq, apiKeys } from "@workspace/db";
import type { Env } from "./index";
import { TtlCache } from "./ttl-cache";

const API_KEY_TTL_MS = 60_000;
const LAST_USED_WRITE_MS = 10 * 60_000;
const apiKeyCache = new TtlCache<{ id: string; workspaceId: string; lastUsedAt: Date | null } | null>(API_KEY_TTL_MS);

export type Caller =
  | { kind: "internal"; workspaceId: string }
  | { kind: "api"; workspaceId: string };

export function unauthorized(): Response {
  return Response.json({ ok: false, error: "Missing or invalid credentials" }, { status: 401 });
}

export function forbidden(): Response {
  return Response.json({ ok: false, error: "Forbidden" }, { status: 403 });
}

/** Constant-time comparison for the internal secret / API key comparisons. */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let out = 0;
  for (let i = 0; i < a.length; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return out === 0;
}

async function sha256Hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(input),
  );
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Resolves who this request is from. `callerKind` + `callerWorkspaceId` are
 * the caller already resolved by the DO/http plumbing (internal calls and
 * the session routes carry their own workspace headers); the remaining
 * surfaces resolve the bearer credential here.
 */
export async function resolveCaller(env: Env, request: Request): Promise<Caller | null> {
  const authHeader = request.headers.get("Authorization") ?? "";
  const bearer = authHeader.startsWith("Bearer ") ? authHeader.slice("Bearer ".length) : "";

  // Internal secret (web proxy, via the WA_WORKER binding). Only meaningful
  // together with the workspace the web app resolved from the session.
  if (bearer && timingSafeEqual(bearer, env.ENGINE_INTERNAL_SECRET)) {
    const workspaceId = request.headers.get("X-Engine-Workspace");
    // A missing header is suspicious: the web app always sends it. Refuse
    // rather than default to anything.
    if (workspaceId && workspaceId.length > 0) {
      return { kind: "internal", workspaceId };
    }
    return null;
  }

  // Per-workspace API key (external integrations).
  if (bearer.startsWith("wa_")) {
    const sha = await sha256Hex(bearer);
    // Cached per isolate for API_KEY_TTL_MS (a revoked key stops working
    // within that window). lastUsedAt is written at most once per
    // LAST_USED_WRITE_MS per key instead of one D1 write per API request.
    const key = await apiKeyCache.get(sha, async () => {
      const db = createDb(env.DB);
      const row = await db
        .select({ id: apiKeys.id, workspaceId: apiKeys.workspaceId, lastUsedAt: apiKeys.lastUsedAt })
        .from(apiKeys)
        .where(eq(apiKeys.keyHash, sha))
        .get();
      return row ?? null;
    });
    if (!key) return null;
    const lastUsed = key.lastUsedAt ? new Date(key.lastUsedAt).getTime() : 0;
    if (Date.now() - lastUsed > LAST_USED_WRITE_MS) {
      key.lastUsedAt = new Date();
      // Best-effort; never fail the request on a write error.
      await createDb(env.DB)
        .update(apiKeys)
        .set({ lastUsedAt: key.lastUsedAt })
        .where(eq(apiKeys.id, key.id))
        .catch(() => {});
    }
    return { kind: "api", workspaceId: key.workspaceId };
  }

  return null;
}

/**
 * Ensure the caller is scoped to the given workspace. Used for endpoints
 * that receive a workspaceId (broadcast, search, ingest, media-upload) so a
 * key holder can't touch another workspace. Returns null when allowed,
 * otherwise a Response to return (401/403).
 */
export function assertCallerWorkspace(caller: Caller, workspaceId: string): Response | null {
  if (caller.workspaceId !== workspaceId) return forbidden();
  return null;
}

// ── Media size caps ─────────────────────────────────────────────────────────
/** Max bytes accepted for library-media uploads (POST /media/upload). 16 MB. */
export const MAX_MEDIA_UPLOAD_BYTES = 16 * 1024 * 1024;
/** Max bytes accepted for per-message media sends (POST /session/:id/send-media). 64 MB. */
export const MAX_SEND_MEDIA_BYTES = 64 * 1024 * 1024;
// SSRF guard -- shared with the web app, see packages/db lib/safe-url.ts
export { assertSafeOutboundUrl } from "@workspace/db";
