/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCreateWorkspaceRouteImport } from './routes/_auth/create-workspace'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppContactListsRouteImport } from './routes/_app/contact-lists'
import { Route as AppBroadcastsRouteImport } from './routes/_app/broadcasts'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'

const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateWorkspaceRoute = AuthCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppContactListsRoute = AppContactListsRouteImport.update({
  id: '/contact-lists',
  path: '/contact-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsRoute = AppBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AppAccountRoute
  '/automation': typeof AppAutomationRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/contact-lists': typeof AppContactListsRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/pipeline': typeof AppPipelineRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/create-workspace': typeof AuthCreateWorkspaceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/media': typeof ApiMediaRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AppAccountRoute
  '/automation': typeof AppAutomationRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/contact-lists': typeof AppContactListsRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/pipeline': typeof AppPipelineRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/create-workspace': typeof AuthCreateWorkspaceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/media': typeof ApiMediaRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/broadcasts': typeof AppBroadcastsRoute
  '/_app/contact-lists': typeof AppContactListsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/create-workspace': typeof AuthCreateWorkspaceRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/media': typeof ApiMediaRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/account'
    | '/automation'
    | '/broadcasts'
    | '/contact-lists'
    | '/contacts'
    | '/inbox'
    | '/integrations'
    | '/pipeline'
    | '/search'
    | '/settings'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/api/media'
    | '/api/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/account'
    | '/automation'
    | '/broadcasts'
    | '/contact-lists'
    | '/contacts'
    | '/inbox'
    | '/integrations'
    | '/pipeline'
    | '/search'
    | '/settings'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/api/media'
    | '/api/auth/verify-email'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/accept-invite'
    | '/_app/account'
    | '/_app/automation'
    | '/_app/broadcasts'
    | '/_app/contact-lists'
    | '/_app/contacts'
    | '/_app/inbox'
    | '/_app/integrations'
    | '/_app/pipeline'
    | '/_app/search'
    | '/_app/settings'
    | '/_auth/create-workspace'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/media'
    | '/api/auth/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-workspace': {
      id: '/_auth/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof AuthCreateWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact-lists': {
      id: '/_app/contact-lists'
      path: '/contact-lists'
      fullPath: '/contact-lists'
      preLoaderRoute: typeof AppContactListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcasts': {
      id: '/_app/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AppBroadcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBroadcastsRoute: typeof AppBroadcastsRoute
  AppContactListsRoute: typeof AppContactListsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBroadcastsRoute: AppBroadcastsRoute,
  AppContactListsRoute: AppContactListsRoute,
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCreateWorkspaceRoute: typeof AuthCreateWorkspaceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCreateWorkspaceRoute: AuthCreateWorkspaceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
